### ISSUE TITLE
Cannot open toasts in different positions

### ISSUE THREAD

**Issue by iJungleboy** [Foxandxss/angular-toastr#175] opened 2016-04-22 06:26 UTC
I had a scenario where I wanted to open toasts in different positions on the screen. In my case I wanted to use it to catch a click on the background around a modal-dialog, and then show one "leaving - click to save" on the top left and a "leaving - click to leave without saving" to the top right. I wanted them apart so that users wouldn't accidentally press the wrong button and loose their work. 

My default scenario opens toasts on top-right, and so I thought I'll just run another toast on top-left using the configuration as the third parameter on the info-toast. 

This doesn't work. The main toasting system creates a div around all toasts, and my new save-on-top-left was added to the same list - on the top-right. 

I believe there are various valid cases where toasts would want to be on different parts of the screen, so I would recommend supporting that.

**Comment by Foxandxss** [comment] 2016-04-22 08:36
I have a not about that in the README and this is a duplicate of a few issues already. It will come, eventually. I just need to find time between dayJob and lot of other projects seeking attention.

Cheers.

**Closed by Foxandxss** 2016-04-22 08:36 UTC
